import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className="navbar bg-neutral text-neutral-content">
            <a className="btn btn-ghost normal-case text-xl">Standings</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
